CREATE TABLE ROLE (
    ID serial PRIMARY KEY,
    ROLE VARCHAR(50)
);

CREATE TABLE USERS (
	ID serial PRIMARY KEY,
    USER_NAME VARCHAR(50),
	ROLE_ID int REFERENCES ROLE(ID)
);

CREATE TABLE RULES (
    ID serial PRIMARY KEY,
    RULE VARCHAR(50)
);

CREATE TABLE ROLE_RULES (
    ID serial PRIMARY KEY,
    ROLE_ID int REFERENCES ROLE(ID),
	RULE_ID int REFERENCES RULES(ID)
);

CREATE TABLE CATEGORY (
    ID serial PRIMARY KEY,
    CATEGORY VARCHAR(50)
);

CREATE TABLE STATE (
    ID serial PRIMARY KEY,
    STATE VARCHAR(50)
);

CREATE TABLE ITEM (
    ID serial PRIMARY KEY,
    ITEM VARCHAR(50),
	USER_ID int REFERENCES USERS(ID),
	CATEGORY_ID int REFERENCES CATEGORY(ID),
	STATE_ID int REFERENCES STATE(ID)
);

CREATE TABLE COMMENTS (
    ID serial PRIMARY KEY,
    COMMENT VARCHAR(50),
	ITEM_ID int REFERENCES ITEM(ID)
);

CREATE TABLE ATTACHS (
    ID serial PRIMARY KEY,
    ATTACH VARCHAR(50),
	ITEM_ID int REFERENCES ITEM(ID)
);

