CREATE TABLE AUTHOR (
	ID serial PRIMARY KEY,
    NAME_AUTHOR VARCHAR(50)
);

CREATE TABLE BOOK (
    ID serial PRIMARY KEY,
    TITLE VARCHAR(50),
	PRICE int,
	AUTHOR_ID int REFERENCES AUTHOR(ID)
	
);

SELECT NAME_AUTHOR AS "Автор",
	TITLE AS "Название книги"
FROM AUTHOR
JOIN BOOK ON AUTHOR.ID = BOOK.AUTHOR_ID;

SELECT NAME_AUTHOR AS "Автор",
	B.TITLE AS "Название книги",
	B.PRICE AS "Цена книги"
FROM AUTHOR
JOIN BOOK AS B ON AUTHOR.ID = B.AUTHOR_ID;

SELECT NAME_AUTHOR AS "Автор",
	B.TITLE AS "Название книги",
	B.PRICE*0.85 AS "Цена книги со скидкой 15%"
FROM AUTHOR
JOIN BOOK AS B ON AUTHOR.ID = B.AUTHOR_ID;
