INSERT INTO ROLE (ROLE) VALUES ('Admin');
INSERT INTO ROLE (ROLE) VALUES ('User');

INSERT INTO RULES (RULE) VALUES ('Full access');
INSERT INTO RULES (RULE) VALUES ('Delete');
INSERT INTO RULES (RULE) VALUES ('Read');
INSERT INTO RULES (RULE) VALUES ('Write');

INSERT INTO ROLE_RULES (ROLE_ID, RULE_ID) VALUES (1, 2);
INSERT INTO ROLE_RULES (ROLE_ID, RULE_ID) VALUES (2, 3);
INSERT INTO ROLE_RULES (ROLE_ID, RULE_ID) VALUES (2, 4);

INSERT INTO USERS (USER_NAME, ROLE_ID) VALUES ('Alex', 1);
INSERT INTO USERS (USER_NAME, ROLE_ID) VALUES ('Artem', 1);

INSERT INTO CATEGORY (CATEGORY) VALUES ('Important');
INSERT INTO CATEGORY (CATEGORY) VALUES ('Common');

INSERT INTO STATE (STATE) VALUES ('Done');
INSERT INTO STATE (STATE) VALUES ('Not processed');
INSERT INTO STATE (STATE) VALUES ('In process');

INSERT INTO ITEM (ITEM, USER_ID, CATEGORY_ID, STATE_ID) VALUES ('Access to directory', 2, 2, 2);
INSERT INTO ITEM (ITEM, USER_ID, CATEGORY_ID, STATE_ID) VALUES ('Problems with the OS', 1, 1, 3);

INSERT INTO COMMENTS (COMMENT, ITEM_ID) VALUES ('Please, let`s do access', 1);
INSERT INTO COMMENTS (COMMENT, ITEM_ID) VALUES ('System not loading', 2);

INSERT INTO ATTACHS (ATTACH, ITEM_ID) VALUES ('item.txt', 1);
INSERT INTO ATTACHS (ATTACH, ITEM_ID) VALUES ('screenshot.jpg', 2);

